[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
decorations = "Buttonless"
dynamic_title = false
# startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14.3

[mouse]
hide_when_typing = true

[general]
import = [
    "~/.config/alacritty/kanagawa-dragon.toml.toml"
]
